title: Mohsen Shayan
email: m0sen91@yahoo.co.uk
description: محسن شایان
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://m0sen.github.io" # the base hostname & protocol for your site
twitter_username: m0sen70
github_username:  m0sen
copyright: "Commons Attribution 4.0 International"

# Build settings
markdown: Markright
kramdown:
coderay_line_numbers: nil
encoding: utf-8
timezone: Asia/Tehran
paginate: 5
paginate_path: "/page:num/"
tag_page_layout: tag_page
tag_page_dir: tag

gems:
  - jalalidate
  - jekyll-paginate
