title: Mohsen Shayan
email: m0sen91@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "m0sen.github.io" # the base hostname & protocol for your site
twitter_username: m0sen70
github_username:  m0sen

# Build settings
markdown: kramdown

encoding: utf-8
paginate: 5
paginate_path: "/page:num/"
tag_page_layout: tag_page
tag_page_dir: tag

gems:
  - jalalidate
  - jekyll-paginate
